apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy-ns
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJqZW5raW5zODAuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5WTNKbFpEcFRZV2xBY0dGNWRHMDROZz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
